# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='owner',
            new_name='team_owner',
        ),
    ]
