# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_event_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostScore', models.DecimalField(decimal_places=0, max_digits=2)),
                ('GuestScore', models.DecimalField(decimal_places=0, max_digits=2)),
                ('HostPoints', models.DecimalField(decimal_places=0, max_digits=2)),
                ('GuestPoints', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('Round', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B', to='games.Team')),
                ('Host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A', to='games.Team')),
            ],
        ),
        migrations.AddField(
            model_name='globalstat',
            name='Match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Match'),
        ),
    ]
