# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_goal_redcard_shots_yellowcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shots',
            old_name='count',
            new_name='number',
        ),
    ]
