# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20170531_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shots',
            name='number',
        ),
        migrations.AddField(
            model_name='shots',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
