# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170531_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shots',
            new_name='Shot',
        ),
    ]
